name: pull-request
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
env:
  test_tag: ghcr.io/${{ github.repository }}:test
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pre-commit'
        uses: dycw/action-pre-commit@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repos: |-
            dycw/pre-commit-hook-nitpick
            pre-commit/pre-commit-hooks
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_GHCR_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.test_tag }}
      - run: |
          docker run --rm ${{ env.test_tag }}
