name: pull-request
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
env:
  test_tag: ghcr.io/${{github.repository}}:test
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pre-commit'
        uses: dycw/action-pre-commit@latest
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repos: |-
            dycw/conformalize
            pre-commit/pre-commit-hooks
      - name: Run 'pre-commit'
        uses: dycw/action-pre-commit@latest
        with:
          repos: |-
            dycw/conformalize
            pre-commit/pre-commit-hooks
          token-checkout: ${{secrets.GITHUB_TOKEN}}
          token-uv: ${{secrets.GITHUB_TOKEN}}
  test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login against a Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_GHCR_TOKEN}}
      - name: Build and push Docker images with Buildx
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{env.test_tag}}
      - name: Run 'docker run'
        run: docker run --rm ${{env.test_tag}}
