name: pull-request
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 34 9 * * *
env:
  test_tag: ghcr.io/${{github.repository}}:test
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'pull_request'
        name: Run 'pre-commit' hooks
        uses: dycw/action-run-hooks@latest
        with:
          repos: |-
            pre-commit/pre-commit-hooks
test-publish:
  runs-on: ubuntu-latest
  steps:
    - name: Check out repo
      uses: actions/checkout@v6
    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login against a Docker registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GH_GHCR_TOKEN}}
    - name: Build and push Docker images with Buildx
      uses: docker/build-push-action@v6
      with:
        load: true
        tags: ${{env.test_tag}}
    - name: Run 'docker run'
      run: docker run --rm ${{env.test_tag}}
