name: push
on:
  push:
    branches:
      - master
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag latest commit
        uses: dycw/action-tag@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Install 'uv'
        uses: astral-sh/setup-uv@v7
      - name: Install 'bump-my-version'
        run: uv tool install --reinstall bump-my-version
      - name: Run 'bump-my-version show current_version'
        id: version
        run: |
          VERSION=$(uv tool run bump-my-version show current_version)
          echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.version.outputs.tagname }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.tagname }}
            type=semver,pattern={{major}},value=${{ steps.version.outputs.tagname }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_GHCR_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
        env:
          PACKAGE_VISIBILITY: public
